version: '2'
services:
  flask_app:
    image: 'registry.hub.docker.com/javabinsec/learndevops:flaskapp'
    environment:
      - "PORT:5000"
    ports:
      - "80:5000"
    volumes:
      - ./:/app
